"""DB worker adapter. No file/env playlist mappings; only explicit DB plans.

POST create/insert is never automatically retried. An outstanding durable intent
must be confirmed by exact read-back before another mutation is permitted.
"""
import json
import os
import re
import subprocess
import sys
from pathlib import Path

import requests

API = 'https://www.googleapis.com/youtube/v3/'
PLAYLIST_ID = re.compile(r'[A-Za-z0-9_-]{10,100}')
VIDEO_ID = re.compile(r'[A-Za-z0-9_-]{11}')
URL = re.compile(r'https://(?:music|www)\.youtube\.com/playlist\?list=([A-Za-z0-9_-]{10,100})')


class ReconciliationRequired(RuntimeError):
    pass


class QuotaBoundReached(RuntimeError):
    pass


class Budget:
    def __init__(self, limit=5000):
        if not isinstance(limit, int) or not 1 <= limit <= 5000:
            raise ValueError('Invalid YouTube quota bound')
        self.limit = limit
        self.used = 0

    def charge(self, method):
        cost = 1 if method == 'GET' else 50
        if self.used + cost > self.limit:
            raise QuotaBoundReached('youtube_quota_bound_reached')
        self.used += cost  # Count attempted calls, including unknown outcomes.


def validate_plan(plan):
    ids = plan.get('videoIds')
    expected = plan.get('expectedUrl')
    if not isinstance(ids, list) or not ids or len(ids) > 1000 or any(not isinstance(v, str) or not VIDEO_ID.fullmatch(v) for v in ids) or len(ids) != len(set(ids)):
        raise ValueError('Invalid YouTube video plan')
    if expected not in ('', 'NEW') and (not isinstance(expected, str) or not URL.fullmatch(expected)):
        raise ValueError('Invalid YouTube binding')
    if not isinstance(plan.get('title'), str) or not plan['title'].strip() or len(plan['title']) > 150 or not isinstance(plan.get('description'), str) or len(plan['description']) > 4000:
        raise ValueError('Invalid YouTube metadata')
    if not isinstance(plan.get('artists'), int) or plan['artists'] < 1:
        raise ValueError('Invalid YouTube artist count')


def discover_plan(source, search=None):
    from youtube_music_transfer import load_ytmusic, parse_report_tracks, search_youtube_track
    report = source['sourceReport']
    queries = parse_report_tracks(report)
    if not queries or len(queries) > 1000:
        raise ValueError('Invalid YouTube source report')
    if search is None:
        ytmusic = load_ytmusic()  # Unauthenticated discovery; no OAuth files.
        cache, stats = {}, {}
        def search(query):
            candidate = search_youtube_track(ytmusic, query, cache, stats=stats)
            if any(stats.get(key) for key in ('quota_errors', 'authentication_errors', 'provider_errors')):
                raise RuntimeError('youtube_discovery_failed')
            return candidate
    ids, artists = [], set()
    for query in queries:
        candidate = search(query)
        if not candidate:
            continue
        video = candidate.get('videoId')
        if not isinstance(video, str) or not VIDEO_ID.fullmatch(video):
            raise ValueError('Invalid discovered video')
        if video in ids:
            continue
        ids.append(video)
        artists.add(query.get('lineup_artist') or query['artist'])
    plan = {
        'slug': source['slug'], 'editionYear': source['editionYear'], 'expectedUrl': source['expectedUrl'],
        'title': report['playlist_name'],
        'description': f"Listen to the announced artists for {report.get('festival') or report['playlist_name']}. Generated by Festival Radar.",
        'videoIds': ids, 'artists': len(artists), 'sourceTracks': len(queries),
    }
    validate_plan(plan)
    return plan


def publish_plan(plan, request, guard, state, progress, *, quota_limit=5000):
    validate_plan(plan)
    budget = Budget(quota_limit)
    desired = plan['videoIds']
    verified = 0

    def checkpoint(complete=False):
        progress({'verifiedTracks': verified, 'totalTracks': len(desired), 'quotaUsed': budget.used, 'complete': complete})

    def call(method, resource, **kwargs):
        budget.charge(method)
        guard()  # Adapter also re-fences after any token refresh.
        return request(method, API + resource, **kwargs)

    def pages(resource, params):
        result, seen, total = [], set(), None
        for _ in range(200):
            page = call('GET', resource, params=params)
            items = page.get('items')
            if not isinstance(items, list):
                raise ReconciliationRequired('youtube_invalid_readback')
            reported_total = page.get('pageInfo', {}).get('totalResults')
            if not isinstance(reported_total, int) or reported_total < 0 or (total is not None and total != reported_total):
                raise ReconciliationRequired('youtube_incomplete_readback')
            total = reported_total
            result.extend(items)
            token = page.get('nextPageToken')
            if not token:
                if len(result) != total:
                    raise ReconciliationRequired('youtube_incomplete_readback')
                return result
            if token in seen or not items:
                raise ReconciliationRequired('youtube_unbounded_readback')
            seen.add(token)
            params = {**params, 'pageToken': token}
        raise ReconciliationRequired('youtube_unbounded_readback')

    def metadata(playlist_id, owner):
        items = pages('playlists', {'part': 'snippet,status', 'id': playlist_id, 'maxResults': 50})
        if len(items) != 1 or items[0].get('id') != playlist_id or items[0].get('snippet', {}).get('channelId') != owner:
            raise ReconciliationRequired('youtube_ownership_readback_failed')
        return items[0]

    def content(playlist_id):
        items = pages('playlistItems', {'part': 'id,snippet', 'playlistId': playlist_id, 'maxResults': 50})
        item_ids, video_ids = [], []
        for position, item in enumerate(items):
            snippet = item.get('snippet', {})
            resource = snippet.get('resourceId', {})
            item_id, video = item.get('id'), resource.get('videoId')
            if not isinstance(item_id, str) or not item_id or item_id in item_ids or snippet.get('position') != position or snippet.get('playlistId') != playlist_id or resource.get('kind') != 'youtube#video' or not isinstance(video, str) or not VIDEO_ID.fullmatch(video):
                raise ReconciliationRequired('youtube_invalid_ordered_readback')
            item_ids.append(item_id)
            video_ids.append(video)
        return items, video_ids

    try:
        channels = pages('channels', {'part': 'id', 'mine': 'true', 'maxResults': 50})
        if len(channels) != 1 or not channels[0].get('id'):
            raise ReconciliationRequired('youtube_owner_ambiguous')
        owner = channels[0]['id']
        current_state = state('read')
        creating = plan['expectedUrl'] in ('', 'NEW')
        playlist_id = current_state['playlistId'] if creating else URL.fullmatch(plan['expectedUrl']).group(1)
        description = plan['description']
        if creating:
            description += f"\n[{current_state['marker']}]"
            creation_metadata = current_state.get('creationMetadata') or {'title': plan['title'], 'description': description}
            if not playlist_id and current_state['sent']:
                matches = [item['id'] for item in pages('playlists', {'part': 'snippet,status', 'mine': 'true', 'maxResults': 50})
                           if item.get('snippet', {}).get('channelId') == owner and item.get('snippet', {}).get('description') == creation_metadata['description'] and item.get('snippet', {}).get('title') == creation_metadata['title']]
                if len(matches) != 1:
                    raise ReconciliationRequired('youtube_create_unknown_no_resend')
                playlist_id = matches[0]
            if not playlist_id:
                # Charge before reserving so quota exhaustion alone leaves no
                # false unknown intent. No provider call occurs until committed.
                budget.charge('POST')
                state('reserve', creation_metadata)
                guard()
                created = request('POST', API + 'playlists', params={'part': 'snippet,status'}, json={'snippet': creation_metadata, 'status': {'privacyStatus': 'public'}})
                playlist_id = created.get('id')
            if not isinstance(playlist_id, str) or not PLAYLIST_ID.fullmatch(playlist_id):
                raise ReconciliationRequired('youtube_invalid_created_id')
            created_metadata = metadata(playlist_id, owner)
            actual = created_metadata.get('snippet', {})
            if current_state['playlistId']:
                valid_creation = actual.get('description', '').endswith(f"\n[{current_state['marker']}]")
            else:
                valid_creation = actual.get('description') == creation_metadata['description'] and actual.get('title') == creation_metadata['title']
            if not valid_creation:
                raise ReconciliationRequired('youtube_creation_metadata_failed')
            state('bind', playlist_id)

        current_metadata = metadata(playlist_id, owner)
        items, current = content(playlist_id)
        pending = current_state.get('pendingInsert')
        if pending:
            if pending['playlistId'] != playlist_id or current != pending['expectedIds'] or len(current) != len(set(current)):
                raise ReconciliationRequired('youtube_insert_unknown_no_resend')
            state('confirm', pending)
        pending_metadata = current_state.get('pendingMetadata')
        if pending_metadata:
            snippet = current_metadata.get('snippet', {})
            if pending_metadata['playlistId'] != playlist_id or snippet.get('title') != pending_metadata['title'] or snippet.get('description') != pending_metadata['description'] or current_metadata.get('status', {}).get('privacyStatus') != 'public':
                raise ReconciliationRequired('youtube_metadata_unknown_no_resend')
            state('metadata-confirm', pending_metadata)

        # Metadata PUT and deletion by immutable item ID are convergent. Never
        # perform these while an ambiguous insertion could still be in flight.
        snippet = current_metadata.get('snippet', {})
        if snippet.get('title') != plan['title'] or snippet.get('description') != description or current_metadata.get('status', {}).get('privacyStatus') != 'public':
            budget.charge('PUT')
            intent = {'playlistId': playlist_id, 'title': plan['title'], 'description': description}
            state('metadata', intent)
            guard()
            request('PUT', API + 'playlists', params={'part': 'snippet,status'}, json={'id': playlist_id, 'snippet': {'title': plan['title'], 'description': description}, 'status': {'privacyStatus': 'public'}})
            current_metadata = metadata(playlist_id, owner)
            if current_metadata.get('snippet', {}).get('title') != plan['title'] or current_metadata.get('snippet', {}).get('description') != description or current_metadata.get('status', {}).get('privacyStatus') != 'public':
                raise ReconciliationRequired('youtube_metadata_readback_failed')
            state('metadata-confirm', intent)
        while verified < min(len(current), len(desired)) and current[verified] == desired[verified]:
            verified += 1
        checkpoint()
        for item in reversed(items[verified:]):
            call('DELETE', 'playlistItems', params={'id': item['id']})
        _, current = content(playlist_id)
        if current != desired[:verified] or len(current) != len(set(current)):
            raise ReconciliationRequired('youtube_delete_readback_failed')
        for position in range(verified, len(desired)):
            budget.charge('POST')
            intent = {'playlistId': playlist_id, 'expectedIds': desired[:position + 1]}
            state('insert', intent)
            guard()
            request('POST', API + 'playlistItems', params={'part': 'snippet'}, json={'snippet': {'playlistId': playlist_id, 'position': position, 'resourceId': {'kind': 'youtube#video', 'videoId': desired[position]}}})
            _, current = content(playlist_id)
            if current != intent['expectedIds'] or len(current) != len(set(current)):
                raise ReconciliationRequired('youtube_insert_readback_failed')
            state('confirm', intent)
            verified = position + 1
            checkpoint()
        final = metadata(playlist_id, owner)
        _, current = content(playlist_id)
        if current != desired or len(current) != len(set(current)) or final.get('snippet', {}).get('title') != plan['title'] or final.get('snippet', {}).get('description') != description or final.get('status', {}).get('privacyStatus') != 'public':
            raise ReconciliationRequired('youtube_final_readback_failed')
        checkpoint(True)
        guard()
        return {'url': f'https://music.youtube.com/playlist?list={playlist_id}' if creating else plan['expectedUrl'], 'expectedUrl': plan['expectedUrl'], 'artists': plan['artists'], 'tracks': len(desired)}
    except Exception:
        # Count-only progress is durable. Never report partial content as success.
        checkpoint()
        raise


def main():
    mode, input_path, output_path = sys.argv[1:4]
    value = json.loads(Path(input_path).read_text(encoding='utf-8'))
    if mode == 'discover':
        result = discover_plan(value)
    elif mode == 'apply':
        from youtube_music_transfer import youtube_data_api_headers
        # Explicit worker environment only; no legacy default credential paths.
        credentials = Path(os.environ['YOUTUBE_MUSIC_CREDENTIALS_FILE'])
        oauth = Path(os.environ['YOUTUBE_MUSIC_OAUTH_FILE'])
        def state(action, payload=None):
            args = [os.environ['PLAYLIST_GUARD_NODE'], '--experimental-strip-types', os.environ['YOUTUBE_GUARD_SCRIPT'], action]
            reply = subprocess.run(args, input=json.dumps(payload) if payload is not None else None, capture_output=True, text=True, check=True, timeout=20)
            return json.loads(reply.stdout)
        def guard():
            state('read')
        def request(method, url, **kwargs):
            headers = youtube_data_api_headers(credentials, oauth)
            guard()  # Refresh may have waited; fence again immediately pre-call.
            response = requests.request(method, url, headers=headers, timeout=30, **kwargs)
            if response.status_code >= 400:
                raise RuntimeError('youtube_provider_request_failed')
            return response.json() if response.content else {}
        result = publish_plan(value, request, guard, state, lambda data: state('progress', data), quota_limit=int(os.environ.get('YOUTUBE_WORKER_QUOTA_UNITS', '5000')))
    else:
        raise ValueError('Invalid YouTube plan operation')
    Path(output_path).write_text(json.dumps(result), encoding='utf-8')


if __name__ == '__main__':
    try:
        main()
    except QuotaBoundReached:
        sys.stderr.write('youtube_quota_bound_reached\n')
        sys.exit(2)
    except ReconciliationRequired:
        sys.stderr.write('youtube_reconciliation_required\n')
        sys.exit(3)
    except Exception:
        sys.stderr.write('youtube_plan_failed\n')
        sys.exit(1)
