"use client";
import { useEffect, useState } from "react";
import { useLanguage } from "./LanguageProvider";
import { emptyPlannerState, type PlannerState, useLocalPlanner } from "./LocalPlanner";
type Kind = "favorites" | "collections" | "saved-filters" | "plans";
type Document = { id: string; payload: unknown; revision: number; updatedAt: string };
type Conflict = { kind: Kind; local: unknown; remote: Document };
const kinds: Kind[] = ["favorites", "collections", "saved-filters", "plans"];
const labels = {
  en: { title: "Account sync", local: "Your local plan remains available while signed out.", migrate: "Merge this device into my account", replace: "Use account data on this device", sync: "Sync now", syncing: "Syncing…", current: "Everything is synchronized.", conflict: "A newer version exists on another device. Nothing was overwritten.", keepLocal: "Keep this device", keepRemote: "Use other device", share: "Create public plan link", expiry: "Link expiry", copy: "Copy link", copied: "Copied", expired: "Expired links return Not Found.", spotify: "Spotify", connect: "Connect or reconnect Spotify", import: "Import playlists", last: "Last sync", failed: "Sync failed. Reconnect and try again.", login: "Sign in from the Account menu to enable cross-device sync." },
  de: { title: "Konto-Synchronisierung", local: "Dein lokaler Plan bleibt ohne Anmeldung verfügbar.", migrate: "Dieses Gerät mit meinem Konto zusammenführen", replace: "Kontodaten auf diesem Gerät verwenden", sync: "Jetzt synchronisieren", syncing: "Synchronisiere…", current: "Alles ist synchronisiert.", conflict: "Auf einem anderen Gerät gibt es eine neuere Version. Nichts wurde überschrieben.", keepLocal: "Dieses Gerät behalten", keepRemote: "Anderes Gerät verwenden", share: "Öffentlichen Plan-Link erstellen", expiry: "Link-Ablauf", copy: "Link kopieren", copied: "Kopiert", expired: "Abgelaufene Links zeigen „Nicht gefunden“.", spotify: "Spotify", connect: "Spotify verbinden oder neu verbinden", import: "Playlists importieren", last: "Letzte Synchronisierung", failed: "Synchronisierung fehlgeschlagen. Neu verbinden und erneut versuchen.", login: "Im Konto-Menü anmelden, um geräteübergreifend zu synchronisieren." },
  ru: { title: "Синхронизация аккаунта", local: "Без входа локальный план останется доступен.", migrate: "Объединить данные устройства с аккаунтом", replace: "Использовать данные аккаунта на устройстве", sync: "Синхронизировать", syncing: "Синхронизация…", current: "Всё синхронизировано.", conflict: "На другом устройстве есть более новая версия. Ничего не перезаписано.", keepLocal: "Оставить данные устройства", keepRemote: "Взять данные другого устройства", share: "Создать публичную ссылку на план", expiry: "Срок ссылки", copy: "Копировать ссылку", copied: "Скопировано", expired: "Истёкшие ссылки возвращают «Не найдено».", spotify: "Spotify", connect: "Подключить или переподключить Spotify", import: "Импортировать плейлисты", last: "Последняя синхронизация", failed: "Ошибка синхронизации. Переподключитесь и повторите.", login: "Войдите через меню аккаунта, чтобы включить синхронизацию между устройствами." },
} as const;
function payloads(p: ReturnType<typeof useLocalPlanner>): Record<Kind, unknown> { return { favorites: { favoriteFestivals: p.favoriteFestivals, favoriteArtists: p.favoriteArtists }, collections: { playlistFestivals: p.playlistFestivals }, "saved-filters": { savedFilters: p.savedFilters }, plans: { attendance: p.attendance } }; }
function plannerFrom(documents: Partial<Record<Kind, Document>>): PlannerState { const value = (kind: Kind) => (documents[kind]?.payload || {}) as Partial<PlannerState>; return { ...emptyPlannerState, ...value("favorites"), ...value("collections"), ...value("saved-filters"), ...value("plans") }; }
function mergePayload(kind: Kind, remote: unknown, local: unknown) {
  const a = remote as Partial<PlannerState>; const b = local as Partial<PlannerState>;
  if (kind === "favorites") return { favoriteFestivals: Array.from(new Set([...(a.favoriteFestivals || []), ...(b.favoriteFestivals || [])])), favoriteArtists: Array.from(new Set([...(a.favoriteArtists || []), ...(b.favoriteArtists || [])])) };
  if (kind === "collections") return { playlistFestivals: Array.from(new Set([...(a.playlistFestivals || []), ...(b.playlistFestivals || [])])) };
  if (kind === "plans") return { attendance: { ...(a.attendance || {}), ...(b.attendance || {}) } };
  return { ...a, ...b };
}
export function AccountSyncPanel() {
  const planner = useLocalPlanner(); const { language, locale } = useLanguage(); const t = labels[language];
  const [user, setUser] = useState<{ id: string; email: string } | null>(null); const [docs, setDocs] = useState<Partial<Record<Kind, Document>>>({}); const [busy, setBusy] = useState(false); const [status, setStatus] = useState(""); const [conflict, setConflict] = useState<Conflict | null>(null); const [shareUrl, setShareUrl] = useState(""); const [expiry, setExpiry] = useState(""); const [spotifyLast, setSpotifyLast] = useState("");
  async function load() { const me = await fetch("/api/auth/me", { cache: "no-store" }); if (!me.ok) { setUser(null); setDocs({}); return; } setUser((await me.json()).user); const entries = await Promise.all(kinds.map(async (kind) => { const response = await fetch(`/api/sync/${kind}`, { cache: "no-store" }); return [kind, (await response.json()).document] as const; })); setDocs(Object.fromEntries(entries.filter(([, value]) => value))); const spotify = await fetch("/api/spotify/status", { cache: "no-store" }); if (spotify.ok) { const state = await spotify.json(); setSpotifyLast(state.connection?.lastSyncedAt || ""); } }
  useEffect(() => { void load(); const listener = () => void load(); window.addEventListener("festival-radar-authenticated", listener); return () => window.removeEventListener("festival-radar-authenticated", listener); }, []);
  async function put(kind: Kind, payload: unknown, revision: number) { const response = await fetch(`/api/sync/${kind}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ payload, revision }) }); const body = await response.json(); if (response.status === 409) { const latest = await fetch(`/api/sync/${kind}`, { cache: "no-store" }).then((value) => value.json()); setConflict({ kind, local: payload, remote: latest.document }); throw new Error("conflict"); } if (!response.ok) throw new Error(body.error || "Sync failed"); setDocs((current) => ({ ...current, [kind]: body.document })); return body.document as Document; }
  async function synchronize(mode: "merge" | "remote" | "normal" = "normal") { setBusy(true); setStatus(""); setConflict(null); try { if (mode === "remote") { planner.replace(plannerFrom(docs)); setStatus(t.current); return; } const local = payloads(planner); for (const kind of kinds) { const content = mode === "merge" && docs[kind] ? mergePayload(kind, docs[kind]!.payload, local[kind]) : local[kind]; await put(kind, content, docs[kind]?.revision || 0); } if (mode === "merge") planner.merge(plannerFrom(docs)); setStatus(t.current); } catch (reason) { if (!(reason instanceof Error && reason.message === "conflict")) setStatus(reason instanceof Error ? reason.message : t.failed); } finally { setBusy(false); } }
  async function resolve(useLocal: boolean) { if (!conflict) return; setBusy(true); try { if (useLocal) await put(conflict.kind, conflict.local, conflict.remote.revision); else { const next = { ...docs, [conflict.kind]: conflict.remote }; setDocs(next); planner.replace(plannerFrom(next)); } setConflict(null); setStatus(t.current); } catch (reason) { setStatus(reason instanceof Error ? reason.message : t.failed); } finally { setBusy(false); } }
  async function share() { setBusy(true); setStatus(""); try { let plan = docs.plans; if (!plan) plan = await put("plans", payloads(planner).plans, 0); const response = await fetch("/api/share", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ documentId: plan.id, expiresAt: expiry ? new Date(`${expiry}T23:59:59.999Z`).toISOString() : null }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || t.failed); setShareUrl(`${location.origin}/share/${body.share.slug}/`); } catch (reason) { setStatus(reason instanceof Error ? reason.message : t.failed); } finally { setBusy(false); } }
  async function spotifySync() { setBusy(true); setStatus(""); try { const response = await fetch("/api/spotify/sync", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(); setSpotifyLast(new Date().toISOString()); setDocs((value) => ({ ...value, collections: body.document })); } catch { setStatus(t.failed); } finally { setBusy(false); } }
  if (!user) return <section className="plannerSection accountSync"><h2>{t.title}</h2><p>{t.local}</p><strong>{t.login}</strong></section>;
  return <section className="plannerSection accountSync" aria-busy={busy}><div className="sectionHeading"><div><div className="eyebrow">{user.email}</div><h2>{t.title}</h2></div><span aria-live="polite">{busy ? t.syncing : status}</span></div><div className="syncActions"><button disabled={busy} onClick={() => synchronize("merge")}>{t.migrate}</button><button disabled={busy || !Object.keys(docs).length} onClick={() => synchronize("remote")}>{t.replace}</button><button disabled={busy} onClick={() => synchronize()}>{t.sync}</button></div>{conflict && <div className="syncConflict" role="alert"><strong>{t.conflict}</strong><div><button disabled={busy} onClick={() => resolve(true)}>{t.keepLocal}</button><button disabled={busy} onClick={() => resolve(false)}>{t.keepRemote}</button></div></div>}<div className="syncGrid"><div><h3>{t.share}</h3><label>{t.expiry}<input type="date" value={expiry} min={new Date().toISOString().slice(0, 10)} onChange={(event) => setExpiry(event.target.value)} /></label><button disabled={busy} onClick={share}>{t.share}</button>{shareUrl && <div className="shareResult"><a href={shareUrl}>{shareUrl}</a><button onClick={async () => { await navigator.clipboard.writeText(shareUrl); setStatus(t.copied); }}>{t.copy}</button></div>}<small>{t.expired}</small></div><div><h3>{t.spotify}</h3><a className="outlineButton" href="/api/spotify/connect">{t.connect}</a><button disabled={busy} onClick={spotifySync}>{t.import}</button>{spotifyLast && <p>{t.last}: <time>{new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(spotifyLast))}</time></p>}</div></div></section>;
}
